Button and Cards components
FluxityStellar/fluxity-interface pull request #1
Opened 2023-08-17 19:40 UTC by dousdogukan

implement Cards , Buttons and Testable in Storybook

2023-08-18 08:50 UTC, matinkaboli requested changes

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CButton/index.tsx
> +  }
White does not show text.
Withdraw and Testnet look empty from inside

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CButton/index.tsx
> +};
Add {...props} here for the button component

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CButton/index.tsx
> +const CButton = ({ color, content, kind, logo }: ButtonProps) => {
Get ..props in parameters

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CCard/index.tsx
> +      style={{ backgroundColor: bgColor, border: 'solid 1px' + borderColor }}
Use literal strings with ` for border. something like solid 1px ${borderColor}

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CCard/index.tsx
> +  return (
Get ...props here for arguments

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CCard/index.tsx
> +      className={cn(className, 'rounded-[14px] border')}
Set ...props here for div

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CPageCard/index.tsx
> +<CPageCard title={a}></CPageCard>;
remove this

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CPageCard/index.tsx
> +  return (
add interface and props here

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CPageCard/index.tsx
> +  );
Where's the  children?

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CPageCard/index.tsx
> +  return (
Also get ...props here in parameters

2023-08-18 08:50 UTC, matinkaboli commented on src/components/CPageCard/index.tsx
> +      className="flex justify-between w-[1000px] max-w-full px-8 py-5"
Set ...props here

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/AllStream/index.tsx
> +import CButton from '../../components/CButton';
no need to put a blank line in between these 2 imports

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/BlueCard/index.tsx
> +      ></CCard>
Do not close the tag like this

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/CreateStream/index.tsx
> +const CreateStream = () => {
Rename the folder too

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/CreateStreamPurple/index.tsx
> +
Rename to `fluxityLogo` (do not set the first letter of an image uppercase)

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/AllStream/index.tsx
> +import HelpSvg from '../../../public/images/help.svg';
Rename to `CardSvg` to `allStreamLogo` (change to file name too)

Rename `helpSvg` to `helpLogo` (do not set the first letter of an image uppercase)

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/Documentation/index.tsx
> +    <div className="w-[480px] h-[230px]">
Cards must not have fixed `height`

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/Documentation/index.tsx
> +          users with the most unique experience.{' '}
remove {' '}

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/Summary/index.tsx
> +
Rename to `summaryLogo` (images are camelCase)

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/Summary/index.tsx
> +  return (
Rename to `SummaryCard` (folder too)

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/Summary/index.tsx
> +        className="flex flex-col justify-between w-full px-3 py-4"
Summary must use `CPageCard`

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/Summary/index.tsx
> +          <Image src={SummarySvg} alt="summary" />
Images should have a fixed `width` and `height`

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/WelcomeToFluxity/index.tsx
> +import CCard from '../../components/CCard';
No Blank line between Vector and CCard.

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/WelcomeToFluxity/index.tsx
> +import CCard from '../../components/CCard';
`VectorSvg` should be renamed to `welcomeLogo` 
images are camelCase

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/WelcomeToFluxity/index.tsx
> +import CCard from '../../components/CCard';
vector.svg should be renamed to `welcome.svg`

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/WelcomeToFluxity/index.tsx
> +    <div className="w-[985px] h-[267px]">
No fixed height here

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/WelcomeToFluxity/index.tsx
> +  return (
Rename to `WelcomeToFluxityCard`
Folder too.

2023-08-18 08:50 UTC, matinkaboli commented on src/containers/WhiteCard/index.tsx
> +    </div>
Do not close the tag like this. Close like `/>`

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/AllStream.stories.ts
Rename this file to AllStreamCard

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/AllStream.stories.ts
> +import AllStream from '../containers/AllStream';
Rename to AllStreamCard

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/Button2.stories.ts
Rename to CButton.stories..

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/CCard.stories.ts
> +
Rename to WelcomeToFluxityCard

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/CreateStream.stories.ts
rename to CreateStreamCard

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/CreateStreamPurple.stories.ts
Rename to `CreateStreamPurpleCard`

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/Documentation.stories.ts
rename to `DocumentationCard`

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/Documentation.stories.ts
> +export const Orange: Story = {};
Rename to `DocumentationCard`

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/Summary.stories.ts
Rename to SummaryCard

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/Summary.stories.ts
> +import Summary from '../containers/Summary';
Rename

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/Summary.stories.ts
> +  title: 'Components/CCard',
Summary uses `CPageCard`. So use `Components/CPageCard` for title

2023-08-18 08:50 UTC, matinkaboli commented on src/stories/WhiteCard.stories.ts
> +export const White: Story = {};
rename to WhiteCard

2023-08-18 08:50 UTC, matinkaboli commented on tailwind.config.ts
> +    './src/styles/**/*.{js,ts,jsx,tsx,mdx}',
Remove and add only `src` itself.

`./src/**/*.......`

2023-08-18 09:15 UTC, ceydae requested changes

2023-08-18 09:15 UTC, ceydae commented on src/components/CCard/index.tsx
> +const CCard = ({ children, bgColor, borderColor, className }: CardProps) => {
Add ...props in parameters here

2023-08-18 09:15 UTC, ceydae commented on src/components/CCard/index.tsx
> +      className={cn(className, 'rounded-[14px] border')}
Add {...props} here

2023-08-18 09:15 UTC, ceydae commented on src/components/CPageCard/index.tsx
> +    </CCard>
Where's thie children prop?

2023-08-18 09:15 UTC, ceydae commented on src/components/CPageCard/index.tsx
> +      className="flex justify-between w-[1000px] max-w-full px-8 py-5"
Add {...props} here.

2023-08-18 09:15 UTC, ceydae commented on src/components/CPageCard/index.tsx
> +const CPageCard = () => {
Add interface and parameters for CPageCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/AllStream/index.tsx
> +import CButton from '../../components/CButton';
No blank line is needed between these imports

2023-08-18 09:15 UTC, ceydae commented on src/containers/AllStream/index.tsx
> +import CButton from '../../components/CButton';
Rename CardSvg to cardLogo
Rename HelpSvg to helpLogo

2023-08-18 09:15 UTC, ceydae commented on src/containers/AllStream/index.tsx
Rename to AllStreamCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/AllStream/index.tsx
> +  return (
Rename to AllStreamCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/AllStream/index.tsx
> +      <CCard
Cards should not have a fixed height

2023-08-18 09:15 UTC, ceydae commented on src/containers/AllStream/index.tsx
> +          <Image src={CardSvg} width="540" alt="logo" />
Image should be moved a bit lower to cover the border

2023-08-18 09:15 UTC, ceydae commented on src/containers/BlueCard/index.tsx
> +      ></CCard>
Close like `/>`

2023-08-18 09:15 UTC, ceydae commented on src/containers/CreateStream/index.tsx
Rename to `CreateStreamCard`

2023-08-18 09:15 UTC, ceydae commented on src/containers/CreateStream/index.tsx
> +  return (
Rename to CreateStreamCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/CreateStream/index.tsx
> +        className="flex justify-between w-full h-full px-8 py-5"
CreateStreamCard should use `CPageCard` not `CCard`. Add `title` and `children` properly.

2023-08-18 09:15 UTC, ceydae commented on src/containers/CreateStreamPurple/index.tsx
rename to `CreateStreamPurpleCard`

2023-08-18 09:15 UTC, ceydae commented on src/containers/CreateStreamPurple/index.tsx
> +const CreateStreamPurple = () => {
Rename to CreateStreamCardPurpleCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/CreateStreamPurple/index.tsx
> +import CButton from '../../components/CButton';
No blank line is needed between these imports

2023-08-18 09:15 UTC, ceydae commented on src/containers/CreateStreamPurple/index.tsx
> +import CButton from '../../components/CButton';
Change LogoSvg to `fluxityLogo` 
images are camelCase

2023-08-18 09:15 UTC, ceydae commented on src/containers/CreateStreamPurple/index.tsx
> +    <div className="w-[480px] h-[230px]">
Remove the fixed height.

2023-08-18 09:15 UTC, ceydae commented on src/containers/Documentation/index.tsx
Rename to `DocumentationCard`

2023-08-18 09:15 UTC, ceydae commented on src/containers/Documentation/index.tsx
> +    <div className="w-[480px] h-[230px]">
Remove the fixed height here.

2023-08-18 09:15 UTC, ceydae commented on src/containers/Summary/index.tsx
> +import SummarySvg from '../../../public/images/summary.svg';
Rename to summaryLogo

2023-08-18 09:15 UTC, ceydae commented on src/containers/Summary/index.tsx
Rename to SummaryCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/Summary/index.tsx
> +import CCard from '../../components/CCard';
Summary uses CPageCard instead of CCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/Summary/index.tsx
> +const Summary = () => {
Rename to SummaryCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/Summary/index.tsx
> +      <CCard
Use CPageCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/Summary/index.tsx
> +          <Image src={SummarySvg} alt="summary" />
Add witdth and height here for image

2023-08-18 09:15 UTC, ceydae commented on src/containers/WelcomeToFluxity/index.tsx
Rename to WelcomeToFluxityCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/WelcomeToFluxity/index.tsx
> +import VectorSvg from '../../../public/images/vector.svg';
Rename to welcomeLogo

2023-08-18 09:15 UTC, ceydae commented on src/containers/WelcomeToFluxity/index.tsx
> +import VectorSvg from '../../../public/images/vector.svg';
Rename the file to welcome.svg

2023-08-18 09:15 UTC, ceydae commented on src/containers/WelcomeToFluxity/index.tsx
> +const WelcomeToFluxity = () => {
Rename to WelcomeToFluxityCard

2023-08-18 09:15 UTC, ceydae commented on src/containers/WelcomeToFluxity/index.tsx
> +    <div className="w-[985px] h-[267px]">
Remove the fixed height here.

2023-08-18 09:15 UTC, ceydae commented on src/containers/WhiteCard/index.tsx
> +      ></CCard>
Do not close like this. close like />

2023-08-18 09:15 UTC, ceydae commented on src/stories/AllStream.stories.ts
Rename to AllStreamCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/AllStream.stories.ts
> +import AllStream from '../containers/AllStream';
rename

2023-08-18 09:15 UTC, ceydae commented on src/stories/AllStream.stories.ts
> +export const Blue2: Story = {};
Rename to AllStreamCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/Button2.stories.ts
Rename to CButton

2023-08-18 09:15 UTC, ceydae commented on src/stories/Button2.stories.ts
> +
These don't show because the text is hidden

2023-08-18 09:15 UTC, ceydae commented on src/stories/CCard.stories.ts
Rename to WelcomeToFluxityCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/CCard.stories.ts
> +import WelcomeToFluxity from '../containers/WelcomeToFluxity';
Rename to WelcomeToFluxityCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/CCard.stories.ts
> +export const Blue: Story = {};
Rename to WelcomeToFluxityCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/AllStream.stories.ts
> +export const Blue2: Story = {};
Rename to AllStreamCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/CreateStream.stories.ts
Rename to `CreateStreamCard`

2023-08-18 09:15 UTC, ceydae commented on src/stories/CreateStream.stories.ts
> +  title: 'Components/CCard',
CreateStreamCard uses CPageCard. So but it in `Components/CPageCard` for title.

2023-08-18 09:15 UTC, ceydae commented on src/stories/CreateStream.stories.ts
> +export const Createstream: Story = {};
Rename to CreateStreamCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/CreateStreamPurple.stories.ts
Rename to CreateStreamPurpleCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/CreateStreamPurple.stories.ts
> +import CreateStreamPurple from '../containers/CreateStreamPurple';
rename

2023-08-18 09:15 UTC, ceydae commented on src/stories/CreateStreamPurple.stories.ts
> +export const Purple: Story = {};
Rename to CreateStreamPurpleCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/Documentation.stories.ts
Rename to DocumentationCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/Documentation.stories.ts
> +import Documentation from '../containers/Documentation';
rename

2023-08-18 09:15 UTC, ceydae commented on src/stories/Documentation.stories.ts
> +export const Orange: Story = {};
Rename to DocumentationCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/Summary.stories.ts
Rename to SummaryCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/Summary.stories.ts
> +import Summary from '../containers/Summary';
rename

2023-08-18 09:15 UTC, ceydae commented on src/stories/Summary.stories.ts
> +  title: 'Components/CCard',
Change the title and use Components/CPageCard because summary uses CPageCard

2023-08-18 09:15 UTC, ceydae commented on src/stories/WhiteCard.stories.ts
> +  title: 'Components/CCard',
Use `CPageCard`

2023-08-18 09:15 UTC, ceydae commented on src/stories/WhiteCard.stories.ts
> +export const White: Story = {};
Rename to WhiteCard

2023-08-18 09:15 UTC, ceydae commented on tailwind.config.ts
> +    './src/styles/**/*.{js,ts,jsx,tsx,mdx}',
Remove these 4 lines and add 1 line instead:

`'./src/**/*.{js,ts,jsx,tsx,mdx}'`

2023-08-19 12:54 UTC, ceydae commented on src/components/CPageCard/index.tsx
> +      <div className="w-full">{title}</div>
Check if `title` is not undefined or null, then use it inside the component.

Something like `{title && <......}`

2023-08-19 12:54 UTC, ceydae commented on src/components/CPageCard/index.tsx
> +      <div className={dividerStyle}></div>
Do not close the tag like this. Close like />

2023-08-20 10:58 UTC, merged