Stream details design
FluxityStellar/fluxity-interface pull request #30
Opened 2023-11-18 19:03 UTC by dousdogukan

implement CStreamDetails design page ,
add new colors to tailwind,
add svgs for stream details

2023-11-19 15:52 UTC, ceydae requested changes
1. Use mock data from the swagger
2. Add all fields to the summary (create a file called summaryFields.ts)

2023-11-19 15:52 UTC, ceydae commented on src/components/CStreamDetailsStatus/index.tsx
> +  type: 'Active' | 'Expired' | 'Pending';
change the type to 'ongoing' | 'expired' | 'pending'

2023-11-19 15:52 UTC, ceydae commented on src/components/CStreamDetailsStatus/index.tsx
> +  let statusStyle;
give status style a default value (pending for example, and then remove the last else if)

2023-11-19 15:52 UTC, ceydae commented on src/containers/StreamDetails/index.tsx
> +  const StreamDetailsTitle = (
rename to mainTitle

2023-11-19 15:52 UTC, ceydae commented on src/containers/StreamDetails/index.tsx
> +  );
move to StatusCard file

2023-11-19 15:52 UTC, ceydae commented on src/containers/StreamDetails/index.tsx
> +                      d="M0.824463 10C0.824463 4.47715 5.30162 0 10.8245 0H201.824V48H10.8245C5.30161 48 0.824463 43.5229 0.824463 38V10Z"
move the SVG code to another file called StreamProgress

<StreamProgress progress={0 to 100}

2023-11-19 15:52 UTC, ceydae commented on src/containers/StreamDetails/index.tsx
> +                <div className="border border-white w-[85%] rounded-xl bg-[#442cd6] pl-[-5px]">
move this to another file called BlueCard

2023-11-19 15:52 UTC, ceydae commented on src/containers/StreamDetails/index.tsx
> +                <span>Total amount</span>
Add other fields of the stream according the design

2023-11-19 15:52 UTC, ceydae commented on src/models.ts
> +}
remove this

2023-11-20 13:26 UTC, ceydae requested changes

2023-11-20 13:26 UTC, ceydae commented on src/components/CSummaryField/index.tsx
move this to streamdetails folder

2023-11-20 13:26 UTC, ceydae commented on src/containers/StreamDetails/StatusCard.tsx
make 2 different status cards, 1. ReceiverStatusCard 2. SenderStatusCard

2023-11-20 13:26 UTC, ceydae commented on src/containers/StreamDetails/StreamProgress.tsx
> +  progress: string;
rename to completionPercentage

2023-11-20 13:26 UTC, ceydae commented on src/components/CStreamDetailsStatus/index.tsx
rename CStreamStatusButton

2023-11-20 13:26 UTC, ceydae commented on src/components/CStreamDetailsStatus/index.tsx
> +const CStreamDetailsStatus = ({ type, label }: CStreamDetailsStatusProps) => {
remove label

2023-11-20 13:26 UTC, ceydae commented on src/containers/StreamDetails/index.tsx
> +        <StatusCard />
check address

1. no address = ""
2. address = sender (SenderStatusCard)
3. address = recevier (ReceiverStatusCard)

2023-11-20 15:27 UTC, dousdogukan commented on src/components/CSummaryField/index.tsx
This component will also be used in CreateStream summary.

2023-11-20 19:24 UTC, ceydae approved these changes

2023-11-20 19:24 UTC, merged